version: '3'

services:
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    expose:
      - 9000
    volumes:
      - ../${APP_NAME}:/var/www/html
    env_file:
      - .env
    networks:
      - local-network
  db:
    image: mariadb:latest
    user: mysql
    ports:
      - 3306
    volumes:
      - ./.data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - local-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/front.conf:/etc/nginx/conf.d/default.conf
      - ../${APP_NAME}:/var/www/html
    networks:
      - local-network

networks:
  local-network:
    external: true